### ISSUE TITLE
🍃Remove unused ktor dependencies

### ISSUE THREAD

**Issue by Xanax-C-137** [FantasyFrontiers/FantasyFrontiers#35]

**Comment by PIYUSH-69** [comment]
can you assign this to me

**Comment by voodoods** [comment]
Hi! :) 

I've provided PR #38 to resolve this before seeing the comment above. So please consider to assign @PIYUSH-69 instead of myself, as I missed writing an assignment request first. Feel free to use PR as a backup if needed or just delete it if obsolete.

**Comment by PIYUSH-69** [comment]
@voodoods 
Thank you bro..
