### ISSUE TITLE
🏹 Item Class Implementation

### ISSUE THREAD

**Issue by CoasterFreakDE** [FantasyFrontiers/FantasyFrontiers#40]
The task involves creating a class for potential items in our game world. The class will serve as the blueprint for all items that players can interact with. It's crucial to decide between naming this class `Material` or `Item`.

#### Objectives:

1. **Naming**: Decide on a suitable class name. Given the absence of 3D world entities and considering items like swords, the name `Item` is favored over `Material`.
  
2. **Attributes**: 
   - `name`: The name of the item as it will appear in-game.
   - `translationKey`: A key derived from the item name for localization purposes.
   - `maxItemStack`: How many of this item could be stacked in a inventory slot (for later usage) – default 99 or 1
   - Additional attributes as needed, with the caveat that durability will not be implemented.

3. **Methods**: 
   - Any utility methods that might be necessary for future features.

#### Dependencies:

- None; this is foundational and doesn't depend on the completion of other tasks.

#### Technical Approach:

- Create a Kotlin class with the decided name.
- Implement attributes and methods as per the objectives.

**Comment by vivekmahindrakar** [comment]
can you give the location (path) where the Item class needs to be implemented?

**Comment by vivekmahindrakar** [comment]
how do i build the project?...there is not proper steps given in readme file

**Comment by CoasterFreakDE** [comment]
You can just use `gradle build`. I will add proper instructions over the next few days.
